# Generated by Django 5.2.17 on 2026-08-30 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0006_welcome_email_sent_at_per_engagement'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('new_bid', 'New bid'), ('deadline', 'Deadline reminder'), ('policy_event', 'Policy event'), ('digest', 'Digest'), ('welcome_engagement', 'Welcome email'), ('password_reset', 'Password reset')], max_length=30)),
                ('success', models.BooleanField()),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='bids.bid')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
