# Generated by Django 5.1.4 on 2026-08-28 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('sign_in', 'Sign in'), ('sign_in_failed', 'Failed sign in'), ('sign_out', 'Sign out'), ('session_revoke', 'Session revoked'), ('bid_create', 'Bid created'), ('bid_update', 'Bid updated'), ('bid_soft_delete', 'Bid soft-deleted'), ('bid_restore', 'Bid restored'), ('conflict_resolution', 'Sync conflict resolved'), ('user_create', 'User created'), ('user_update', 'User updated'), ('role_change', 'Role changed'), ('password_reset', 'Password reset'), ('manual_sync_trigger', 'Manual sync triggered')], max_length=32)),
                ('field', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'audit entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
