# Generated by Django 5.1.4 on 2026-08-28 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='bids.bid'),
        ),
    ]
