# Generated by Django 5.1.4 on 2026-08-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditentry_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditentry',
            name='action',
            field=models.CharField(choices=[('sign_in', 'Sign in'), ('sign_in_failed', 'Failed sign in'), ('sign_out', 'Sign out'), ('session_revoke', 'Session revoked'), ('bid_create', 'Bid created'), ('bid_update', 'Bid updated'), ('bid_soft_delete', 'Bid soft-deleted'), ('bid_restore', 'Bid restored'), ('conflict_resolution', 'Sync conflict resolved'), ('user_create', 'User created'), ('user_update', 'User updated'), ('role_change', 'Role changed'), ('password_reset', 'Password reset'), ('password_change', 'Password changed'), ('manual_sync_trigger', 'Manual sync triggered')], max_length=32),
        ),
    ]
