# Generated by Django 5.1.4 on 2026-08-28 07:51

import apps.bids.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('canonical_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=200, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['canonical_name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS bids_arrival_seq;",
            reverse_sql="DROP SEQUENCE IF EXISTS bids_arrival_seq;",
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('arrival_seq', models.BigIntegerField(default=apps.bids.models.next_arrival_seq, editable=False, unique=True)),
                ('uid', models.UUIDField(blank=True, null=True, unique=True)),
                ('source', models.CharField(choices=[('sheet', 'Sheet'), ('app', 'App')], default='app', max_length=10)),
                ('sheet_row', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('engagement_from', models.DateField(blank=True, null=True)),
                ('engagement_to', models.DateField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, max_length=100)),
                ('initiation_mode', models.CharField(blank=True, max_length=100)),
                ('procurement_type', models.CharField(blank=True, max_length=100)),
                ('is_goods', models.BooleanField(default=False)),
                ('is_works', models.BooleanField(default=False)),
                ('is_service', models.BooleanField(default=False)),
                ('tender_id', models.CharField(blank=True, max_length=100)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('prebid_date', models.DateField(blank=True, null=True)),
                ('prebid_time', models.TimeField(blank=True, null=True)),
                ('submission_date', models.DateField(blank=True, db_index=True, null=True)),
                ('submission_time', models.TimeField(blank=True, null=True)),
                ('submission_status', models.CharField(blank=True, max_length=100)),
                ('result', models.CharField(blank=True, max_length=100)),
                ('security_mode', models.CharField(blank=True, max_length=100)),
                ('security_amount_raw', models.TextField(blank=True)),
                ('security_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('security_currency', models.CharField(blank=True, choices=[('BDT', 'BDT'), ('USD', 'USD')], max_length=3)),
                ('credit_facility_raw', models.TextField(blank=True)),
                ('credit_facility', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('credit_facility_currency', models.CharField(blank=True, choices=[('BDT', 'BDT'), ('USD', 'USD')], max_length=3)),
                ('bg_issue_date', models.DateField(blank=True, null=True)),
                ('bg_reference', models.CharField(blank=True, max_length=100)),
                ('bg_bank', models.CharField(blank=True, max_length=150)),
                ('bg_expiry_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('locally_overridden', models.JSONField(blank=True, default=list)),
                ('missing_from_sheet', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bids', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bids', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='bids.client')),
                ('bid_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bids_as_bid_manager', to='bids.person')),
                ('cam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bids_as_cam', to='bids.person')),
                ('engaged_resources', models.ManyToManyField(blank=True, related_name='engaged_bids', to='bids.person')),
                ('sales_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bids_as_sales_resource', to='bids.person')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='bids.team')),
            ],
            options={
                'ordering': ['arrival_seq'],
            },
        ),
        migrations.CreateModel(
            name='BidNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_notes', to=settings.AUTH_USER_MODEL)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='bids.bid')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
