# Generated by Django 5.1.4 on 2026-08-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_seed_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='initiation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
