# Generated by Django 5.1.4 on 2026-08-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_bid_initiation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='deadline_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
