# Generated by Django 5.2.17 on 2026-08-30 17:51
#
# §Phase 19: engagement and cost tracking. BidEngagement replaces the plain
# engaged_resources M2M with a through model — copy_existing_engagements below
# moves every existing (bid, person) row across (days=0, dates null, per the
# phase spec) before the M2M is repointed at the new table, so none of that
# data is lost.

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def copy_existing_engagements(apps, schema_editor):
    OldThrough = apps.get_model("bids", "bid_engaged_resources")
    BidEngagement = apps.get_model("bids", "BidEngagement")

    BidEngagement.objects.bulk_create(
        [
            BidEngagement(
                bid_id=row.bid_id,
                person_id=row.person_id,
                engaged_from=None,
                engaged_to=None,
                days=0,
                convenience_bill=Decimal("0"),
            )
            for row in OldThrough.objects.all()
        ]
    )


def restore_old_m2m_rows(apps, schema_editor):
    """Reverse: rebuild the old bare-M2M through rows from BidEngagement, so
    unapplying this migration doesn't strand the engaged_resources link."""
    OldThrough = apps.get_model("bids", "bid_engaged_resources")
    BidEngagement = apps.get_model("bids", "BidEngagement")

    OldThrough.objects.bulk_create(
        [
            OldThrough(bid_id=row.bid_id, person_id=row.person_id)
            for row in BidEngagement.objects.all()
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_bid_deadline_alert_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-arrival_seq']},
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='welcome_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BidCostLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('BDT', 'BDT'), ('USD', 'USD')], default='BDT', max_length=3)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_lines', to='bids.bid')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engaged_from', models.DateField(blank=True, null=True)),
                ('engaged_to', models.DateField(blank=True, null=True)),
                ('days', models.PositiveIntegerField(default=0)),
                ('convenience_bill', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='bids.bid')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='bids.person')),
            ],
            options={
                'ordering': ['person__canonical_name'],
            },
        ),
        migrations.RunPython(copy_existing_engagements, restore_old_m2m_rows),
        # Django refuses AlterField for adding/removing through= on an M2M
        # ("you cannot alter to or from M2M fields, or add or remove
        # through="): remove the bare M2M (dropping its now-copied-from
        # hidden join table) and add it back pointed at BidEngagement.
        migrations.RemoveField(
            model_name='bid',
            name='engaged_resources',
        ),
        migrations.AddField(
            model_name='bid',
            name='engaged_resources',
            field=models.ManyToManyField(blank=True, related_name='engaged_bids', through='bids.BidEngagement', to='bids.person'),
        ),
        migrations.AddConstraint(
            model_name='bidengagement',
            constraint=models.UniqueConstraint(fields=('bid', 'person'), name='unique_bid_engagement_person'),
        ),
    ]
