# Generated by Django 5.2.17 on 2026-08-30 18:18
#
# §Phase 20 item 5: welcome_email_sent_at moves from Person to BidEngagement.
# Phase 19 placed it on Person, but Phase 20's "never sends twice for the
# same bid" / "resend button per person per bid" are per-(bid, person), which
# a Person-level timestamp can't represent. No data migration needed — the
# field was never populated (no welcome-email feature existed to set it).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_engagement_and_cost_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='welcome_email_sent_at',
        ),
        migrations.AddField(
            model_name='bidengagement',
            name='welcome_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
