# Generated by Django 5.2.17 on 2026-08-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0006_welcome_email_sent_at_per_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='pending_sheet_append',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bid',
            name='sheet_append_error',
            field=models.TextField(blank=True),
        ),
    ]
