# Generated by Django 5.1.4 on 2026-08-28 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0004_bid_deadline_alert_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=150)),
                ('default_in_app', models.BooleanField(default=True)),
                ('default_email', models.BooleanField(default=False)),
                ('applies_to_roles', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='DeadlineReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('applies_to_roles', models.JSONField(blank=True, default=list)),
                ('users', models.ManyToManyField(blank=True, related_name='extra_deadline_reminder_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['days_before'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
                ('label', models.CharField(max_length=150)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by_sync', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='settings_admin.choicelist')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'constraints': [models.UniqueConstraint(fields=('list', 'value'), name='unique_choicelist_value')],
            },
        ),
        migrations.CreateModel(
            name='DeadlineReminderSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_reminders_sent', to='bids.bid')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_records', to='settings_admin.deadlinereminderrule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bid', 'rule'), name='unique_bid_rule_reminder_sent')],
            },
        ),
        migrations.CreateModel(
            name='UserCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(max_length=50)),
                ('granted', models.BooleanField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'capability'), name='unique_user_capability')],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPolicyOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app', models.BooleanField(blank=True, null=True)),
                ('email', models.BooleanField(blank=True, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='settings_admin.notificationpolicy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_policy_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'policy'), name='unique_user_policy_override')],
            },
        ),
    ]
